version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '3001:${PORT}'
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/dev/app
      - /home/dev/app/node_modules
    environment:
      PORT: ${PORT}
      STAGE: ${STAGE}
