name: Cleanup Deployment
on:
  pull_request:
    types:
      - closed

env:
  PREVIEW_URL: https://${{ github.base_ref }}__${{ github.head_ref }}.surge.sh

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup Surge
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - run: |
          npm install --global surge
          surge teardown ${{ env.PREVIEW_URL }} --token ${{ secrets.SURGE_TOKEN }}
