name: 'Linter'
on:
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: main

      - name: Setup Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 17.3.0

      - name: Run ESLint
        run: |
          yarn install --immutable --immutable-cache
          yarn lint
