name: 'PR Checker'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
    branches:
      - 'main'
      - 'staging'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: thehanimo/pr-title-checker@v1.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          pass_on_octokit_error: false
          configuration_path: '.github/json/PR-checker.config.json'
